stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lze/testapp
      pushRemote: true
      registry: harbor.capitalonline.net/test/cp:v1
- name: run
  steps:
  - runScriptConfig:
      image: harbor.capitalonline.net/test/cp:v1
      shellScript: bash bin/run_api.sh
timeout: 60
notification: {}
